/* global React */
// Floor plan zones — bounds are % of the floor plan image (left, top, width, height).
// Each zone has architectural qualities that get fed into the agent's "spatial reading".

const ZONES = [
  { id: "quiet_refuge_1", label: "Quiet Refuge", short: "QR-1",
    bounds: [1.5, 2.7, 11.5, 20.5],
    qualities: { lux: "dim", noise: "very low", density: "solo", biophilia: "high (plants on roof, side window)", exit: "single door, visible", scale: "small, enclosed" },
    description: "A small enclosed alcove with a single sofa, plant troughs along the roof line, one door. Intended for solo decompression." },
  { id: "quiet_refuge_2", label: "Quiet Refuge", short: "QR-2",
    bounds: [1.5, 25.5, 11.5, 13.5],
    qualities: { lux: "dim", noise: "very low", density: "solo", biophilia: "moderate (one plant, side window)", exit: "single door, visible", scale: "very small" },
    description: "A second compact refuge — slightly smaller. Window strip on the left, single seat. Highly contained." },
  { id: "therapy_1", label: "Therapy Room 1", short: "T1",
    bounds: [15.0, 3.8, 11.8, 21.5],
    qualities: { lux: "warm lamplight", noise: "low", density: "dyadic", biophilia: "plant by window, soft rug", exit: "single door to corridor", scale: "small" },
    description: "Two armchairs around a small round rug, table lamp, single therapist desk, plant by the window. Intimate 1:1 space." },
  { id: "therapy_2", label: "Therapy Room 2", short: "T2",
    bounds: [27.8, 3.8, 13.1, 21.5],
    qualities: { lux: "warm lamplight + skylight", noise: "low", density: "dyadic", biophilia: "small bloom on table", exit: "single door", scale: "small" },
    description: "Mirror of T1 — armchairs around a rug, a small floral on the side table. Used for locum coverage." },
  { id: "therapy_3", label: "Therapy Room 3", short: "T3",
    bounds: [41.3, 3.8, 14.2, 21.5],
    qualities: { lux: "warm + lamp accent", noise: "low", density: "dyadic", biophilia: "plant by window", exit: "single door", scale: "small" },
    description: "Same vocabulary as T1/T2. Dr Olivia's room." },
  { id: "art_therapy", label: "Art Therapy Room 4", short: "T4",
    bounds: [55.9, 3.8, 15.6, 21.7],
    qualities: { lux: "bright, daylight + tasklight", noise: "low-medium", density: "small group", biophilia: "courtyard window", exit: "single door + courtyard adjacency", scale: "medium" },
    description: "Wooden table for 4, sink, easel, shelves of materials. Tactile and visually rich. Sky's room." },
  { id: "group_therapy", label: "Group Therapy Room", short: "G",
    bounds: [72.0, 4.2, 21.5, 26.4],
    qualities: { lux: "even daylight", noise: "circular voice", density: "8-person circle", biophilia: "courtyard view", exit: "single door, not visible from all seats", scale: "large round" },
    description: "Large round rug with 8 chairs in a perfect circle. Direct sightlines across the group. Sister Anna's space." },
  { id: "reception", label: "Reception & Waiting", short: "R",
    bounds: [1.5, 39.6, 26.8, 37.3],
    qualities: { lux: "dim ambient", noise: "low hum", density: "open, multi-party", biophilia: "plants along the windows", exit: "main entrance not visible from sofas", scale: "very large" },
    description: "Curved reception desk and three sofa clusters facing inward. Long visual sightlines; no direct view of therapy doors or main entrance from most seats." },
  { id: "courtyard", label: "Courtyard", short: "C",
    bounds: [30.4, 32.9, 28.3, 32.0],
    qualities: { lux: "outdoor daylight", noise: "wind + light foot traffic", density: "passing", biophilia: "very high (planted island, two benches)", exit: "ringed by doorways", scale: "outdoor pocket" },
    description: "Central planted island with two benches. Open to sky. Visible from every clinical room — a green anchor in the plan." },
  { id: "tea_pause", label: "Tea / Pause Area", short: "TP",
    bounds: [29.8, 65.5, 20.9, 19.3],
    qualities: { lux: "warm + window strip", noise: "medium hum, cups, talk", density: "small social cluster", biophilia: "moderate (courtyard adjacency, plants)", exit: "open to circulation", scale: "medium" },
    description: "Round wooden table, low-backed armchairs. Liminal — between consultations and exit. Mrs Tang, Pearl, Karen tend to settle here." },
  { id: "staff_lounge", label: "Staff Lounge & Offices", short: "SL",
    bounds: [51.7, 58.0, 29.4, 29.4],
    qualities: { lux: "low, no exterior window", noise: "low hum", density: "small staff cluster", biophilia: "indoor planter only", exit: "staff door only", scale: "medium, deep plan" },
    description: "Round table, planter, bookshelves, B. Offices. No window. Where therapists reset between clients." },
  { id: "records", label: "Records (staff only)", short: "REC",
    bounds: [81.0, 54.0, 12.2, 17.0],
    qualities: { lux: "task light", noise: "very low", density: "solo / pair", biophilia: "side window, planter strip", exit: "single door", scale: "small office" },
    description: "Records office. Single desk, file shelving, restricted access." },
  { id: "f_washroom", label: "Female Washroom", short: "WF",
    bounds: [82.6, 32.1, 11.0, 9.5],
    qualities: { lux: "bright fluorescent", noise: "tiled echo", density: "private cubicles", biophilia: "none", exit: "single door", scale: "small" },
    description: "Standard washroom. Acoustically reflective." },
  { id: "m_washroom", label: "Male Washroom", short: "WM",
    bounds: [82.6, 42.5, 11.0, 9.5],
    qualities: { lux: "bright fluorescent", noise: "tiled echo", density: "private cubicles", biophilia: "none", exit: "single door", scale: "small" },
    description: "Standard washroom." },
  { id: "storage", label: "Storage", short: "ST",
    bounds: [82.0, 71.5, 11.6, 13.5],
    qualities: { lux: "off / task only", noise: "silent", density: "empty", biophilia: "none", exit: "single door", scale: "very small" },
    description: "Storage. Generally unoccupied." },
  { id: "staff_f_wash", label: "Staff Female Washroom", short: "SWF",
    bounds: [51.7, 85.4, 11.7, 7.4],
    qualities: { lux: "bright", noise: "tiled", density: "solo", biophilia: "none", exit: "single door", scale: "very small" },
    description: "Staff washroom." },
  { id: "staff_m_wash", label: "Staff Male Washroom", short: "SWM",
    bounds: [63.7, 85.4, 11.4, 7.4],
    qualities: { lux: "bright", noise: "tiled", density: "solo", biophilia: "none", exit: "single door", scale: "very small" },
    description: "Staff washroom." },
  { id: "entrance", label: "Main Entrance", short: "ENT",
    bounds: [15.1, 91.2, 21.5, 8.2],
    qualities: { lux: "daylight, transitional", noise: "street + interior bleed", density: "passing", biophilia: "planted strip outside", exit: "the exit itself", scale: "threshold" },
    description: "The threshold. No seating. Directly outdoor when stepped through." },
];

window.ZONES = ZONES;
